name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t los23/app_int:latest .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Tag Docker image
        run: docker tag los23/app_int:latest ${{ secrets.DOCKER_USERNAME }}/los23/app_int:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/los23/app_int:latest

#
  #    - name: Deploy to Cloud Provider
    #    env:
    #      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #    CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
      #  run: |
         # docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


          
          # Add your deployment commands here, for example:
          # Deploy to Kubernetes
          # kubectl set image deployment/myapp myapp=${{ secrets.DOCKER_USERNAME }}/myapp:latest --record
